version: "3.9"

services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
      - DATABASE_URL=mongodb+srv://<username>:<password>@cluster0.mongodb.net/<databaseName>
      - GOOGLE_CLIENT_ID=<your-google-client-id>
      - GOOGLE_CLIENT_SECRET=<your-google-client-secret>
      - GOOGLE_CALLBACK_URL=http://localhost:5000/auth/google/callback
      - SESSION_SECRET=<your-session-secret>
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
